name = "lovable-project"
compatibility_date = "2024-01-01"

[build]
command = "npm install && npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[env.production]
# Force npm usage instead of bun
vars = { NODE_PACKAGE_MANAGER = "npm" }